version: '3.9'

services:
  backend:
    build: ./backend
    expose:
      - 8000

  frontend:
    build: ./frontend
    expose:
      - 80

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
